# Generated by Django 3.0.8 on 2021-12-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=50, verbose_name='Código')),
                ('nombre_proveedor', models.CharField(max_length=50, verbose_name='Nombre')),
                ('domicilio_proveedor', models.CharField(max_length=150, verbose_name='Domicilio')),
                ('telfijo_proveedor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('movil_proveedor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('email_proveedor', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('zipcode_proveedor', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_proveedor'],
            },
        ),
    ]
