# Generated by Django 3.0.8 on 2021-12-08 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=150, unique=True, verbose_name='Nacionalidad Producto')),
            ],
            options={
                'verbose_name_plural': 'Nacionalidad',
                'ordering': ['nacionalidad'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(max_length=10, unique=True, verbose_name='Código Producto')),
                ('nombre_producto', models.CharField(max_length=150, unique=True, verbose_name='Nombre Producto')),
                ('descripcion_producto', models.TextField(blank=True, null=True, verbose_name='Características')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio Unitario')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Categoria', verbose_name='Categoria Producto')),
                ('id_nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Nacionalidad', verbose_name='Nacionalidad Producto')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto'],
            },
        ),
    ]
