# Generated by Django 3.0.8 on 2021-12-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=150, unique=True, verbose_name='Pais')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['pais'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_cliente', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni_cliente', models.CharField(max_length=10, verbose_name='DNI')),
                ('domicilio_cliente', models.CharField(max_length=150, verbose_name='Domicilio')),
                ('telfijo_cliente', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('movil_cliente', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('zipcode_cliente', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Pais', verbose_name='Pais')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido_cliente'],
            },
        ),
    ]
