# Generated by Django 3.0.8 on 2021-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vendedor', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_vendedor', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni_vendedor', models.CharField(max_length=10, verbose_name='DNI')),
                ('domicilio_vendedor', models.CharField(max_length=150, verbose_name='Domicilio')),
                ('codigo_vendedor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código')),
                ('sucursal', models.CharField(choices=[('0', 'Seleccionar Sucursal'), ('1', 'Casa Central'), ('2', 'Sucursal Centro 1'), ('3', 'Sucursal Centro 2'), ('4', 'Sucursal Oeste 1'), ('5', 'Sucursal Sur 1')], default='0', max_length=1, verbose_name='Sucursal')),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
                'ordering': ['apellido_vendedor'],
            },
        ),
    ]
